Adding maturity field
ga4gh-discovery/ga4gh-service-info pull request #43
Opened 2019-07-25 16:12 UTC by andrewyatz

Issue #33 raised a need for a maturity field. This adds that field in, types it to an enum and makes it a required field. The enum requirement could be removed at a later date.

2019-07-29 13:37 UTC, mpanik approved these changes

2019-07-29 14:29 UTC, mcupak requested changes
Can we make it not required? I'd bet most people won't need it.

2019-07-29 14:38 UTC, jrambla commented
The ones requiring it are the *clients* of the service, not the owners. It must be required if it should be of any utility, on the contrary we could end up in the same situation that we are today. Forcing to choose an option would make the owners to think about it.

2019-07-29 16:52 UTC, andrewyatz commented
I agree with @jrambla that it should be required and why I added `unknown` in to give those implementing it a way to shortcut the response. If we were to remove `unknown` then I push for it to be optional

2019-08-15 15:31 UTC, mcupak commented
Agreed to rename to `environment` and replace `unknown` with `null` (i.e. make optional).

2019-08-15 15:32 UTC, mcupak approved these changes
LGTM now

2019-08-15 15:39 UTC, merged